<?php

// Git Add Command
define('CONFIGURATION_GIT_STATUS', 'git status ');
define('CONFIGURATION_GIT_ADD', 'git add -A ');
define('CONFIGURATION_GIT_COMMIT', 'git commit -m \'Auto Generated\'');

define('CONFIGURATION_GIT_WHOAMI', 'whoami ');



/**
 * Implements configuration_gitpost_help.
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function configuration_gitpost_help($path, $arg) {
  switch ($path) {
    case "admin/help#configuration_gitpost":
      return '<p>'.  t("This is the first help from my new module") .'</p>';
      break;
  }
}

function configuration_git_after_configuration_write_exports($filename) {
	
	$return_var = 0;
	$command = CONFIGURATION_GIT_ADD ;//. $filename;
	$output = array();
	exec($command . ' 2>&1', $output, $return_var);
	if ($return_var!=0)
	{
		// TODO check to see if this is correct using platform name
		$result = getcwd();
		// TODO check to see if this is correct using platform name
	
	}
	
	$return_var = 0;
	$command = CONFIGURATION_GIT_COMMIT ; // . $filename;
	
	exec($command . ' 2>&1', $output, $return_var);
	if ($return_var!=0)
	{
		// TODO error handliyng
	
	}
	$stuff = implode(':',$output);
	$log_contents = <<<LOG
Command: $command
Output: $stuff
Result: $return_var

LOG;
	file_put_contents('/var/aegir/platforms/monigle-core.001/sites/test001.local/files/config/whoami.git_test', $log_contents );
}